<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>MLCIWEB_09_Formulir Permohonan Pengecekan Data</name>
   <tag></tag>
   <elementGuidId>a5a82e5a-6c74-445b-b236-9ec883c441af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.sfHover > ul > li.sfHover > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='main-menu']/li[4]/ul/li[8]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6e048d44-f9c5-4539-989e-fbc572d48a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://www.mitsuilease.co.id/form-cust</value>
      <webElementGuid>0c5aa9a3-2adc-4d93-9ba2-28552479e6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Formulir Permohonan Pengecekan Data</value>
      <webElementGuid>89c2ff89-a2b7-40f0-b59e-723ec4682048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-nav&quot;)/ul[@id=&quot;main-menu&quot;]/li[@class=&quot;sfHover&quot;]/ul[1]/li[@class=&quot;sfHover&quot;]/a[1]</value>
      <webElementGuid>9301ac33-e8bf-41a4-aba2-6e5d6ec1ec2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='main-menu']/li[4]/ul/li[8]/a</value>
      <webElementGuid>d57a9570-dc27-48ea-8ecd-5782f4a1f115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Formulir Permohonan Pengecekan Data')]</value>
      <webElementGuid>d8befc0f-f897-42aa-90c1-a3b7ee7e67e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dokumen Persyaratan Pengambilan BPKB'])[1]/following::a[1]</value>
      <webElementGuid>f93b5d91-3148-4a4e-85ea-53fbb1472179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aplikasi Kredit'])[1]/following::a[2]</value>
      <webElementGuid>d201434c-7806-4914-9810-8ab9cd483c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Komentar/Saran'])[1]/preceding::a[2]</value>
      <webElementGuid>0d856518-8ad5-43d3-bb47-6a4002363301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[3]</value>
      <webElementGuid>94bff8b5-551a-4748-8c0f-48669999ecf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Formulir Permohonan Pengecekan Data']/parent::*</value>
      <webElementGuid>ca1d97a6-2adc-4bd5-885e-9a4ac6f222b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://www.mitsuilease.co.id/form-cust')]</value>
      <webElementGuid>884705d4-2e3b-4c4e-b802-38f1c3fb5249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[8]/a</value>
      <webElementGuid>0f9fdeb3-e95b-4957-ab07-9b74a273a50a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://www.mitsuilease.co.id/form-cust' and (text() = 'Formulir Permohonan Pengecekan Data' or . = 'Formulir Permohonan Pengecekan Data')]</value>
      <webElementGuid>6b0a6d03-6a6d-4290-9376-48696691626e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
