<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Attachment</name>
   <tag></tag>
   <elementGuidId>bd85fe0b-33b6-48c1-a7b4-348ad988adb9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div[2]/div/div/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8ae56721-0898-4ba7-b885-ecdd30a434fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>7117da38-5460-4d19-905a-b3caeaab7853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light</value>
      <webElementGuid>72c2bbb8-01ca-4bb7-8a34-dae249617b07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Attachment
			</value>
      <webElementGuid>0da616ec-78e9-4257-8343-e1c8c0b8f796</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;memodetail&quot;]/div[@id=&quot;content&quot;]/div[@class=&quot;card shadow&quot;]/div[2]/div[@class=&quot;pagelayout&quot;]/div[@class=&quot;btn-group&quot;]/span[@class=&quot;btn btn-light&quot;]</value>
      <webElementGuid>52b46e83-c037-4621-8027-9b455734e90c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/div/div/span[2]</value>
      <webElementGuid>040ba7c0-0d09-4085-a0a6-45592aca6af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memo'])[2]/following::span[1]</value>
      <webElementGuid>b2ed329f-2494-4fad-881d-f4d76e7d8dfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Add Mode)'])[1]/preceding::span[5]</value>
      <webElementGuid>ca5f38d5-0b7f-47b6-ace0-9145e4e77f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memo No:'])[1]/preceding::span[6]</value>
      <webElementGuid>b06cdd6e-a9dd-4b98-981a-72e6fc7bbaa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Attachment']/parent::*</value>
      <webElementGuid>56e8cce4-f64a-4935-a16f-7cffdf12518d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span[2]</value>
      <webElementGuid>0f76b113-42bb-4171-883f-fe567a8e90ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
				Attachment
			' or . = '
				Attachment
			')]</value>
      <webElementGuid>707cace3-1f5f-4926-918d-eb5a0742b07e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
