<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Memo</name>
   <tag></tag>
   <elementGuidId>c2f0882a-5402-4a80-9d46-a7784a06512f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.pagelayout > div.btn-group > span.btn.btn-light</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div[2]/div/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>843727bd-0a6e-4e61-9f7e-6d80592ae4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>163800f7-0e53-4cae-8e4e-3d87c64f364a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-light</value>
      <webElementGuid>99c9d1e3-bd7f-4742-85de-9ccb8dff8658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
				Memo
			</value>
      <webElementGuid>ceb9da24-097f-4bb6-80f0-ae14588e10f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;memodetail&quot;]/div[@id=&quot;content&quot;]/div[@class=&quot;card shadow&quot;]/div[2]/div[@class=&quot;pagelayout&quot;]/div[@class=&quot;btn-group&quot;]/span[@class=&quot;btn btn-light&quot;]</value>
      <webElementGuid>17a97262-44b9-46f2-9581-48f333242087</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/div/div/span</value>
      <webElementGuid>6ba65520-bbbe-417a-a4de-a319d0e2d67c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Memo'])[1]/following::span[2]</value>
      <webElementGuid>4aadf102-e2ef-42dc-bc5e-fe5d845633b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Attachment'])[1]/preceding::span[1]</value>
      <webElementGuid>eaaf0eb8-eb35-48e1-9d04-0d0ebaf13457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Add Mode)'])[1]/preceding::span[6]</value>
      <webElementGuid>ca406f7a-fdaa-48d2-82fe-9d0b9b143b69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/span</value>
      <webElementGuid>a63c2e56-acfb-4110-b1f6-461dec94997e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '
				Memo
			' or . = '
				Memo
			')]</value>
      <webElementGuid>84c0a754-637c-46b1-9f0e-4058254520c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
