<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Attachment_fa fa-floppy-o</name>
   <tag></tag>
   <elementGuidId>9d921dd6-1207-43ff-b6a9-dbe6686f71f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-floppy-o</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div[2]/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dcccd7e7-c814-4eb1-ad61-32fa268d7d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8c6511c7-e6d0-4c46-bcf4-c94f83b5de1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-floppy-o</value>
      <webElementGuid>d2ee4d30-c4c1-4d2a-9368-0d6235586c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;memodetail&quot;]/div[@id=&quot;content&quot;]/div[@class=&quot;card shadow&quot;]/div[2]/div[@class=&quot;pagelayout&quot;]/div[@class=&quot;btn-group&quot;]/button[@class=&quot;btn btn-info&quot;]/span[@class=&quot;fa fa-floppy-o&quot;]</value>
      <webElementGuid>3e61e955-fac5-469c-bb71-439c061a1e5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div[2]/div/div/button/span</value>
      <webElementGuid>0f988595-6817-42c5-9e1c-10b420fbf606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button/span</value>
      <webElementGuid>6d74daf8-90db-440c-880c-be88c596be33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
