<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Memo ContentMax 5000 char(s)5000 c_ee4af2</name>
   <tag></tag>
   <elementGuidId>8280a201-f240-4f76-aaf4-672166003daa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.p-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/div/div/div[3]/div[2]/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>57b08ac5-f739-427d-a022-0fa57e28d10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>c1b9eadd-eda7-494c-b1e0-d5123ffd41a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5000</value>
      <webElementGuid>115b822b-bfca-4513-b599-08e7b5f91db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>p-2</value>
      <webElementGuid>85ea473d-61ad-412f-926f-7ed8bb4b4135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;memodetail&quot;]/div[@id=&quot;content&quot;]/div[@class=&quot;card shadow&quot;]/div[2]/div[@class=&quot;pagelayout&quot;]/div[@id=&quot;content&quot;]/div[@class=&quot;card shadow&quot;]/div[@class=&quot;card-body&quot;]/div[@class=&quot;form-inline&quot;]/div[@class=&quot;col-md-10&quot;]/div[@class=&quot;row&quot;]/textarea[@class=&quot;p-2&quot;]</value>
      <webElementGuid>e0d1ca79-891a-4861-a73f-9036f9611d90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/div/div/div[3]/div[2]/div/textarea</value>
      <webElementGuid>3ee90bfd-a7db-4ed6-a745-77a9705745a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4204b8cd-35dd-4088-bf29-c40a1ef17df5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
